[2주차/필수] Android UI 구현 심화 : 디자인 패턴
DO-SOPT-ANDROID/jihyun-bae pull request #8
Opened 2023-10-23 13:23 UTC by jihyunniiii

## Related issue 🛠
- closed #7

## Work Description ✏️
#### 항상 한 종류의 타입만 반복되는 게 아니죠?
- profile recyclerView 구현
- 리스트 최상단에 내 프로필 추가 (스크롤 시에 내 프로필 영역도 같이 스크롤 되어야 함)
- friend 리스트에 멜론 뮤직 추가
- Multi-View Type 사용 시 Sealed Class 사용
- 생일 View Type 추가

## Screenshot 📸
https://github.com/DO-SOPT-ANDROID/jihyun-bae/assets/103172971/814ff4a1-2b66-4ca0-81e1-ad9953ebfab8

## Uncompleted Tasks 😅
- N/A

## To Reviewers 📢
- 데이터 바인딩을 떠나보냈는데요,,, 그래서인지 코드가 많이 더러운 것 같아요,,,, 코리로 혼내주세염 ㅋ.ㅋ
- 그리고 그냥 냅다 ListAdapter 써버림 ㅋ 제송합니다 ~

2023-10-24 05:49 UTC, taeheeL reviewed
깔끔하게 잘하셨네요 
다른 분들 리뷰 후에 다시 오겠습니다 ㅎㅎ

2023-10-24 05:49 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/data/model/local/Profile.kt
> +        fun toMyProfile() = org.sopt.dosopttemplate.domain.model.Profile.MyProfile(
import 해주세요.. 불-편

2023-10-24 05:49 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +    private val viewModel by viewModels<HomeViewModel>()
뷰모델들이 모든 곳에서 viewModel이라는 공통의 이름으로 선언되면 헷갈리지 않을까요?
homeViewModel 이런식으로 바꾸는 게 어떠실지

2023-10-25 07:07 UTC, sohyun127 approved these changes
로로공주 최고👍🏻👍🏻

2023-10-25 07:07 UTC, sohyun127 commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/local/DataSourceImpl/DummyDataSourceImpl.kt
> +                name = "푸루루",
푸루루라는 친구도 있나요?ㅋㅋㅋㅋㅋㅋ신기하네

2023-10-25 07:07 UTC, sohyun127 commented on app/src/main/java/org/sopt/dosopttemplate/data/repository/DummyRepositoryImpl.kt
> +    override fun getMockProfileList() = dummyDataSource.mockProfileList.map { profile ->
오 여기서 매팽하셨군요👍🏻

2023-10-25 07:07 UTC, sohyun127 commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    class MyProfileViewHolder(
가독성과 재사용성을 위해 뷰 홀더 별도의 클래스로 분리하는 것도 좋을듯!!

2023-10-25 07:07 UTC, sohyun127 commented on app/src/main/java/org/sopt/dosopttemplate/presentation/type/ProfileInfoType.kt
> +enum class ProfileInfoType(
깔끔하네유!!

2023-10-26 15:20 UTC, lsakee requested changes
ob분들 미쳤네요 코드

2023-10-26 15:20 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    class MyProfileViewHolder(
그리고 저거 아이템 구별하는게 명확해야될 거 같습니다. 동일성과 내용을 판단하는 로직이 똑같네요!

2023-10-26 15:20 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +        else -> throw Exception("unknown type!!")
에러를 던지기만 하고 있어요

2023-10-26 15:20 UTC, lsakee commented on app/src/main/res/layout/fragment_home.xml
> +            type="org.sopt.dosopttemplate.presentation.home.HomeViewModel" />
요건 언제쓰죠?

2023-10-27 05:35 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/local/DataSourceImpl/DummyDataSourceImpl.kt
> +                name = "푸루루",
지어낸거아님?

2023-10-27 05:41 UTC, librarywon reviewed
수고했습니당 케로로씨

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/local/DataSourceImpl/DummyDataSourceImpl.kt
> +    override val mockProfileList: List<Profile>
아직 힐트는 몰르겠서요..

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/data/model/local/Profile.kt
> +        val birthDay: Int
월 일로 구분하지 않고 LocateDate 클래스를 활용하는 것도 좋을 것 같아요

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/HomeActivity.kt
> +                R.id.menu_my_page -> navigateTo<MyPageFragment>()
미리 만들어두니까 깔끔하다

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +    private val viewModel by viewModels<HomeViewModel>()
흐음 나도 찔리네..

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    class MyProfileViewHolder(
저는 이름으로 했슴둥

2023-10-27 05:41 UTC, librarywon commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +            binding.run {
run { }을 사용하신 이유는 무엇인가요?

2023-10-27 13:48 UTC, l2zh approved these changes
너무 깔끔하다 미쳤ㅋㅋ
나도 휴학할래~~

2023-10-27 13:48 UTC, l2zh commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    }
근데 혹시 이거 뷰타입 다 따로 관리해야되는 이유가 있나요??
전 visible 처리로 할 생각이었는데....

2023-10-27 17:32 UTC, Marchbreeze reviewed
케로케로케로케로케로케로케로케로

2023-10-27 17:32 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +                ivFriendProfile.setImageResource(friendProfile.profileImage)
Coil 라이브러리 활용하는게 성능에 더 도움될 것 같습니다 ~~

2023-10-27 17:32 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/HomeActivity.kt
> +            true
지금 상황에서는 itemId 로 어떤 값이 들어와도 true가 return될 것 같은데, else 처리로 false 처리해주는 로직 설정해두는건 어떨까요?

2023-10-27 17:34 UTC, HAJIEUN02 approved these changes
너무 므찌고 부러운 휴학생,, 고생많으셨슴당 이번 주 세미나도 화이팅💛

2023-10-27 17:34 UTC, HAJIEUN02 commented on app/src/main/AndroidManifest.xml
왕 다음에 폴더링 꿀팁 미미나 열어주세여

2023-10-27 17:34 UTC, HAJIEUN02 commented on app/src/main/java/org/sopt/dosopttemplate/domain/model/Profile.kt
> +sealed class Profile {
sealed class는 처음 배워가요! 나중에 음악 삽입할 때 이런 식으로 데이터 클래스 구분해봐야겠어요 ㅎ ㅎ

2023-10-27 17:34 UTC, HAJIEUN02 commented on app/src/main/res/layout/item_home_my_profile.xml
> +        android:textAppearance="@style/TextAppearance.CaptionM2"
chainStyle이랑 textAppearance, ellipsize 등등.. 첨 보는게 많아서 많이 배워갑니둥

2023-10-27 17:34 UTC, HAJIEUN02 commented on app/src/main/res/values/strings.xml
> +    <string name="home_profile_info_type_birth">선물하기</string>
헐 선물하기까지 구현

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
열심히 준비해 보겠숩니다 ㅎ.ㅎ

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/local/DataSourceImpl/DummyDataSourceImpl.kt
> +    override val mockProfileList: List<Profile>
저두 아직 공부 중 ㅠ 넘 어려워요 ㅠ

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/data/datasource/local/DataSourceImpl/DummyDataSourceImpl.kt
> +                name = "푸루루",
진짜 있음 ㅋㅋ 푸루루 왕 기여븜

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/data/model/local/Profile.kt
> +        fun toMyProfile() = org.sopt.dosopttemplate.domain.model.Profile.MyProfile(
이거 import가 안 되더라구요? ㅠ 방법이 있나요? ㅠ

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/HomeActivity.kt
> +            true
조씀니다 ㅎ.ㅎ 수정할게욤

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeFragment.kt
> +    private val viewModel by viewModels<HomeViewModel>()
헤헤,,, 수정할게요

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    class MyProfileViewHolder(
반영하겠숩니닷 ㅜ

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +            binding.run {
with 함수 안에 또 with 함수를 넣는 식으로 구현하고 싶었는데 이런 식으로 구현하면 안 돼서 run + with로 구현하였습니닷!

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +        else -> throw Exception("unknown type!!")
ㅠㅠ

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/res/layout/fragment_home.xml
> +            type="org.sopt.dosopttemplate.presentation.home.HomeViewModel" />
헉,,, 이거 지우는 거 깜빡했서요 감사티비

2023-10-29 05:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +    }
하암,,, 걍 아무 생각 없이 어떤 data class인지에 따라서 뷰타입 만들어야징 ~ 하고 만들었는데 생각해보니까 따로 만들 필요가 없을 듯요,,,,,? 저두 visible로 처리해서 ㅋ.ㅋ 하암,,,, 수정할게요,,,,,,,,,,,,

2023-10-29 07:51 UTC, pump9918 approved these changes

2023-10-29 07:51 UTC, pump9918 commented on app/src/main/java/org/sopt/dosopttemplate/util/ItemDiffCallback.kt
> +package org.sopt.dosopttemplate.util
ItemDiffCallback은 유저와 콘텐츠를 연결해주는 건가요??

2023-10-29 07:59 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dosopttemplate/util/ItemDiffCallback.kt
> +package org.sopt.dosopttemplate.util
ㅋ.ㅋ 이거 중요한 거니까 혼자 공부해보세요 ㅋㅋ 안 알려줌 !

https://jihyunniiii.notion.site/DiffUtil-ListAdapter-92dddcaf0dfe41cfa94d591a5abff9dc?pvs=4

2023-10-31 13:26 UTC, Sangwook123 reviewed
감탄만 하다갑니다

2023-10-31 13:26 UTC, Sangwook123 commented on app/src/main/java/org/sopt/dosopttemplate/data/model/local/Profile.kt
> +        fun toMyProfile() = org.sopt.dosopttemplate.domain.model.Profile.MyProfile(
직접 작성하면 됩ㄴ다 ㅋㅋ

2023-10-31 13:26 UTC, Sangwook123 commented on app/src/main/java/org/sopt/dosopttemplate/presentation/home/HomeProfileAdapter.kt
> +        else -> throw Exception("unknown type!!")
adapter 초기화할때 처리해주면 댈듯함니다

2023-11-09 16:20 UTC, lsakee approved these changes
LGTM!

2023-11-09 16:21 UTC, merged